import image1 from "./images/1+1.webp" 
import image2 from "./images/interstellar.webp";
import image3 from "./images/600x900.webp";
import image4 from "./images/island.webp"
import image5 from "./images/figthClub.webp"
import image6 from "./images/forest.webp"
import image7 from "./images/ghost.webp"
import image8 from "./images/terminator.webp"
import image9 from "./images/gladiator.webp"
import imageGreenBook from "./images/green-book.webp"
import pulpFiction from "./images/pulpFiction.webp"
import bigKush from "./images/bigKush.webp"
import darkKnight from "./images/darkKnight.webp"
import inception from "./images/inception.webp"
import movie2 from "./images/movie-2.webp"

export const arrayOne = [
  {
    img: image1,
    textH2: "1+1",
    rating: "18+",
    genre1: "драма",
    genre2: "комедия",
    genre3: "",
    time1: "12:45",
    price1: "2D от 35 с.",
    time2: "22:45",
    price2: "2D от 45 с.",
    time3: "",
    price3: "",
    location: "Зал 1",
    urlKey: "tTwFeGArcrs",
  },
  {
    img: image2,
    textH2: "Интерстеллар",
    rating: "16+",
    genre1: "фантастика",
    genre2: "драма",
    genre3: "приключения",
    time1: "9:45",
    price1: "2D от 35 с.",
    time2: "16:30",
    price2: "3D от 45 с.",
    time3: "20:15",
    price3: "2D от 55 с.",
    location: "Зал 2",
    urlKey: "qcPfI0y7wRU",
  },
  {
    img: image3,
    textH2: "Побег из Шоушенка",
    rating: "18+",
    genre1: "биографическое",
    genre2: "драма",
    genre3: "",
    time1: "14:30",
    price1: "3D от 45 с.",
    time2: "18:25",
    price2: "2D от 50 с.",
    time3: "",
    price3: "",
    location: "Зал 3",
    urlKey: "kgAeKpAPOYk",
  },
  {
    img: image4,
    textH2: "Остров проклятых",
    rating: "18+",
    genre1: "триллер",
    genre2: "детектив",
    genre3: "драма",
    time1: "16:30",
    price1: "3D от 35 с.",
    time2: "20:15",
    price2: "2D от 45 с.",
    time3: "",
    price3: "",
    location: "Зал 4",
    urlKey: "_l7R9Rz5URw",
  },
  {
    img: image5,
    textH2: "Бойцовский клуб",
    rating: "18+",
    genre1: "триллер",
    genre2: "криминал",
    genre3: "драма",
    time1: "21:25",
    price1: "3D от 45 с.",
    time2: "",
    price2: "",
    time3: "",
    price3: "",
    location: "Зал 1",
    urlKey: "O1nDozs-LxI",
  },
  {
    img: image6,
    textH2: "Форрест Гамп",
    rating: "18+",
    genre1: "комедия",
    genre2: "драма",
    genre3: "военный",
    time1: "13:10",
    price1: "2D от 25 с.",
    time2: "17:15",
    price2: "2D от 35 с.",
    time3: "",
    price3: "",
    location: "Зал 2",
    urlKey: "otmeAaifX04",
  },
  {
    img: image7,
    textH2: "Унесённые призраками",
    rating: "12+",
    genre1: "аниме",
    genre2: "фэнтези",
    genre3: "приключения",
    time1: "16:30",
    price1: "3D от 45 с.",
    time2: "",
    price2: "",
    time3: "",
    price3: "",
    location: "Зал 3",
    urlKey: "bgxiTkAlQrw",
  },
  {
    img: image8,
    textH2: "Терминатор 2: Судный день",
    rating: "18+",
    genre1: "триллер",
    genre2: "фантастика",
    genre3: "боевик",
    time1: "16:30",
    price1: "3D от 45 с.",
    time2: "21:15",
    price2: "2D от 50 с.",
    time3: "",
    price3: "",
    location: "Зал 4",
    urlKey: "CRRlbK5w8AE",
  },
  {
    img: image9,
    textH2: "Гладиатор",
    rating: "18+",
    genre1: "история",
    genre2: "драма",
    genre3: "боевик",
    time1: "19:15",
    price1: "2D от 50 с.",
    time2: "",
    price2: "",
    time3: "",
    price3: "",
    location: "Зал 2",
    urlKey: "F2Dr7Qb2Zf8",
  },
];

export const arrayTwo = [
  {
    name: "Зеленая книга",
    img: imageGreenBook,
    when: "с 10 мая 2025",
  },

  {
    name: "Криминальное чтиво",
    img: pulpFiction,
    when: "с 12 мая 2025",
  },
  {
    name: "Большой куш",
    img: bigKush,
    when: "с 14 мая 2025",
  },
  {
    name: "Темный рыцарь",
    img: darkKnight,
    when: "с 20 мая 2025",
  },
  {
    name: "Начало",
    img: inception,
    when: "с 24 мая 2025",
  },
  {
    name: "Достучаться до небес",
    img: movie2,
    when: "с 30 мая 2025",
  },
];